// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8k69Tjcf8N5jSowuRy8DUQbKjFsOTDLA',
    appId: '1:60126022461:web:07cd4dbb614390e87a1354',
    messagingSenderId: '60126022461',
    projectId: 'fortune-wheel-c97e9',
    authDomain: 'fortune-wheel-c97e9.firebaseapp.com',
    storageBucket: 'fortune-wheel-c97e9.appspot.com',
    measurementId: 'G-VMQ0G8WFKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1BECzm_7jXGt-qLctbp3MnWlYHIX83yY',
    appId: '1:60126022461:android:c212ac1b6b4acba47a1354',
    messagingSenderId: '60126022461',
    projectId: 'fortune-wheel-c97e9',
    storageBucket: 'fortune-wheel-c97e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKhBeJ8Htbz3ZAQTb7aCJ3a6-ndgd4wGo',
    appId: '1:60126022461:ios:fada7d247238d17c7a1354',
    messagingSenderId: '60126022461',
    projectId: 'fortune-wheel-c97e9',
    storageBucket: 'fortune-wheel-c97e9.appspot.com',
    iosBundleId: 'com.example.fortuneWheel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKhBeJ8Htbz3ZAQTb7aCJ3a6-ndgd4wGo',
    appId: '1:60126022461:ios:eacfaa25284993937a1354',
    messagingSenderId: '60126022461',
    projectId: 'fortune-wheel-c97e9',
    storageBucket: 'fortune-wheel-c97e9.appspot.com',
    iosBundleId: 'com.example.fortuneWheel.RunnerTests',
  );
}
